# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^deploy:'
      - '^ignore:'
  use: github-native

release:
  github:
    owner: sabafly
    name: sabafly-lib
  draft: true
